@baseUrl="http://localhost:8000"
@appjson="application/json"
@accessToken="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInV1aWQiOiJiNWEwNDE0Ni00N2UyLTQ5ZjAtODI4Yi1mNzA0MGU1ZWIwOGQiLCJpYXQiOjE2NjE2NzU5MDMsImV4cCI6MTY2MTY3NTk4OX0.zuvnoHOUn1TREyOpC_BXqXX2nGwm0We8fGwgnoQm3yQ"


### get all contacts 
GET http://localhost:8000/contacts


### get a contact 
GET http://localhost:8000/contacts/1



### create a contact c

POST http://localhost:8000/contacts
Content-Type: application/json
Authorization: "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInV1aWQiOiJiNWEwNDE0Ni00N2UyLTQ5ZjAtODI4Yi1mNzA0MGU1ZWIwOGQiLCJpYXQiOjE2NjE2NzU5MDMsImV4cCI6MTY2MTY3NTk4OX0.zuvnoHOUn1TREyOpC_BXqXX2nGwm0We8fGwgnoQm3yQ"

{
    "primaryPhoneNumber":"+9779841000000",
    "fullName":"Ram Bahadur",
    "userId":1
}



### update post 
PATCH http://localhost:8000/contacts/5
Content-Type: application/json

{
    "userId":1,
    "fullName":"Hari Bahadur"
}


### dele
DELETE http://localhost:8000/contacts/4
